rootProject.name = "prototype-hexagonal"

include 'bootstrap'
include 'bootstrap:node-server-app'
include 'module'
include 'module-test'
include 'config'

// 최상위 'module' 디렉토리에서 시작하여 모듈 포함
includeModulesRecursively(file("${rootDir}/module"))
includeModulesRecursively(file("${rootDir}/module-test"))
includeModulesRecursively(file("${rootDir}/config"))
includeModulesRecursively(file("${rootDir}/bootstrap"))

// 모듈을 재귀적으로 찾아 포함시키는 함수
void includeModulesRecursively(File dir) {
    dir.eachDir { subDir ->
        if (subDir.isDirectory()) {
            if (subDir.name != "src" && new File(subDir, "build.gradle").exists()) {
                // 모듈로 간주하고 include
                String path = subDir.path.replace("${rootDir}" + File.separator, "").replace(File.separator, ':')
                include path
                // 하위 디렉토리에 대해서도 탐색
                includeModulesRecursively(subDir)
            }
        }
    }
}

