bootJar {
    mainClass = 'prototype.hexa.sample.SampleApplication'
    archiveFileName = "${archiveBootFileNameJar}-${version}-sample-app.jar"
    destinationDirectory = file(rootDir)
}

dependencies {
    // 설정모듈
    implementation project(':config:core-config')
    implementation project(':config:third-party-config')
    implementation project(':config:rdb-config')
    implementation project(':config:r2dbc-config')
    implementation project(':config:redis-config')
    implementation project(':config:nosql-config')
    implementation project(':config:kafka-config')
    implementation project(':config:swagger-config')

    // 실행모듈
    implementation project(':module:common')
    implementation project(':module:sample')
    implementation project(':module:membership')
    implementation project(':module:order')

}
