plugins {
    id 'nu.studer.jooq' version '7.1'
    id 'java'
    id 'org.springframework.boot' version "${springBootVersion}"
    id 'io.spring.dependency-management' version "${springManageVersion}"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("org.springframework.boot:spring-boot-starter-data-jdbc")
    implementation("org.springframework.boot:spring-boot-starter-jooq")
    implementation("org.postgresql:postgresql:42.2.5") // PostgreSQL 드라이버

    jooqGenerator("org.postgresql:postgresql:42.2.5") // JOOQ 코드 생성용 드라이버
}


jooq {
    version = '3.15.0'
    configurations {
        main {
            generationTool { // generationTool로 설정 시작
                jdbc {
                    driver = 'org.postgresql.Driver'
                    url = 'jdbc:postgresql://localhost:6432/test'
                    user = 'root'
                    password = 'password'
                }
                generator {
                    name = 'org.jooq.codegen.JavaGenerator'
                    database {
                        name = 'org.jooq.meta.postgres.PostgresDatabase'
                        inputSchema = 'sample'
                    }
                    generate {
                        records = true
                        pojos = true
                    }
                    target {
                        packageName = 'prototype.hexa.asynctest'
                        directory = 'build/generated/jooq'
                    }
                }
            }
        }
    }
}

// sourceSets에 생성된 코드 디렉토리 추가
sourceSets.main.java.srcDir 'build/generated/jooq'
