dependencies {
    // 설정모듈
    implementation project(':prototype-hexagonal:config:core-config')
    implementation project(':prototype-hexagonal:config:rdb-config')
    implementation project(':prototype-hexagonal:config:jooq-config')

    // 실행모듈
    implementation project(':prototype-hexagonal:module-test:async-test')
}
