plugins {
    id "org.springframework.boot" version "${springBootVersion2}"
    id "io.spring.dependency-management" version "${springManageVersion2}"
    id 'java-library'
}

group = "playground-back-end"
version = "1.0.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    api "org.springframework.boot:spring-boot-starter"
    api "org.springframework.boot:spring-boot-starter-web"
    api "org.springframework.boot:spring-boot-starter-webflux"
    api "org.springframework.boot:spring-boot-starter-validation"
}
