dependencies {
    // 설정모듈
    implementation project(':config:core-config')
    implementation project(':config:redis-config')
    implementation project(':config:rabbit-mq-config')
    implementation project(':config:kafka-config')

    // 실행모듈
    implementation project(':module-test:producer-test')
}
