dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-amqp'
    implementation 'org.springframework.kafka:spring-kafka'

    implementation project(':prototype-hexagonal:config:redis-config')
    implementation project(':prototype-hexagonal:module-test:producer-test')
}