server:
  port: 9090

spring:
  application:
    name: Spring AI !!!
  ai:
    model:          # 여러 Chat 모델 사용시 auto-configurations 에서 사용할 모델 설정 필요 ex: openai, ollama
      chat: ollama  # or openai, ollama
      embedding: ollama
    openai:
      embedding:
        options:
          model: bge-m3
      api-key: ${OPENAI_API_KEY}   # 환경변수로 관리 권장
      chat:
        completions-path: /chat/completions
        base-url: https://models.github.ai/inference
        options:
          model: openai/gpt-4.1
#          temperature: 0.7 # 응답의 창의성 여부, 0~1, 낮을수록 사실기반, 높을수록 창의적+거짓확률높음
    ollama:
      chat:
        options:
          model: hf.co/rippertnt/HyperCLOVAX-SEED-Text-Instruct-1.5B-Q4_K_M-GGUF # ToolCalling 사용시 mistral (7B q4 기본 모델로 약 7GB 메모리 필요) 사용
      init:
        pull-model-strategy: when_missing # when_missing, always, never 설정
#      base-url: http://localhost:11434
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: debug

app:
  cli:
    chat:
      enabled: false     # SimpleChatConfig 확인
    rag:
      enabled: false    # RagChatConfig 확인
    filter-expression: ''