# 어플리케이션 커스텀 옵션 추가
app:
  cli:
    enabled: true  # CLI 모드 활성화 여부
  chat:
    default-system-prompt: "한국어를 사용하는 tool 지원 AI 입니다."  # 기본 system prompt

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG  # SimpleLoggerAdvisor 등의 Advisor에서 DEBUG 로그 출력
          tool: DEBUG  # Tool 사용 과련 DEBUG 로그 출력

spring:
  application:
    name: spring-ai-mcp-client
  ai:
    mcp:
      client:
        enabled: true   # MCP Client 활성화
        type: SYNC      # MCP Client 타입 ,ASYNC
        # stdio 콘솔기반 (시스템out 방식)
        stdio:
          connections:
            weather-mcp-server:
              command: /usr/bin/python3              # MCP 서버 실행 Python 경로
              args:
                - -m
                - mcp_weather_server  # MCP 서버 실행 인자
            local-mcp-server:
#              command: /usr/bin/java # java 경로
              command: /Library/Java/JavaVirtualMachines/zulu-21.jdk/Contents/Home/bin/java # java 경로
              args:
                - -jar
                - /Users/myungsubso/Desktop/github-test/my/playground-back-end/spring-ai/mcp-server.jar # mcp 서버 빌드 후 생성된 jar 위치 경로
                - --spring.main.banner-mode=off            # Spring Boot 배너 비활성화
                - --logging.pattern.console=               # 콘솔 로그 패턴 비우기
                - --spring.ai.mcp.server.stdio=true        # STDIO 기반 MCP 서버 활성화
                - --spring.main.web-application-type=none  # 웹 서버 기능 생략 (비웹 모드)
          # MCP 서벗 연동해서 사용할 경우 (sse 방식)
#          sse:
#            connections:
#              local-mcp-server:
#                url: http://localhost:9091
    model:
      chat: openai  # 여러 Chat 모델 사용시 auto-configurations 에서 사용할 모델 설정 필요 예: openai, ollama
    openai:
      api-key: ${OPENAI_API_KEY}  # OpenAI 호출 API를 제공하는 Provider의 경우 아래 내용을 적절히 수정
      chat:
        options:
          model: openai/gpt-4.1-nano  # 모델명 설정
        base-url: https://models.github.ai/inference  # 설정하지 않으면 기본 OpenAI api 호출 주소를 사용
        completions-path: /chat/completions  # OpenAI 기본값은 /v1/chat/completions, github 모델 사용시 아래와 같이 수정
    ollama:
      chat:
        options:
          model: mistral  # Structured Output, Tool Calling 사용시 mistral (7B q4 기본 모델로 약 7GB 메모리 필요) 사용